#!/usr/bin/env python
# Helper script to work with CouchDB design documents and the filesystem

import os
import argparse
import json
import urllib2

from fs2couch import fs_to_ddoc, ddoc_to_fs, script_main


if __name__ == '__main__':

    p = argparse.ArgumentParser(description="""
Reads / writes design documents from CouchDB to a filesystem directory structure,
for ease of development and maintenance. Assumes the directory structure should
be similar to the canonical CouchApp structure, but supports multiple design
documents and multiple languages.""")

    p.add_argument('-i', '--input', metavar='INPUT', type=str, required=True,
                   help="Input URL / directory. If a URL, must be the whole path to the design document")
    p.add_argument('-o', '--output', metavar='OUTPUT', type=str, required=True,
                   help="Output URL / directory. If a URL, must be the root of the CouchDB database")
    args = p.parse_args()

    script_main(args.input, args.output)
